name: Build and deploy GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "public/**"
      - ".github/workflows/**"
      - "package.json"
      - "package-lock.json"

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: Build and Deploy Astro site
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build Astro site
      - name: Build site
        run: npm run build

      # Deploy to gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
